export const GEO = [
  { name: "Austria", code: "AT" },
  { name: "Argentina", code: "AR" },
  { name: "Australia", code: "AU" },
  { name: "Belgium", code: "BE" },
  { name: "Brazil", code: "BR" },
  { name: "Canada", code: "CA" },
  { name: "Chile", code: "CL" },
  { name: "Colombia", code: "CO" },
  { name: "Denmark", code: "DK" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Egypt", code: "EG" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "Norway", code: "NO" },
  { name: "Philippines", code: "PH" },
  { name: "Hungary", code: "HU" },
  { name: "Hong Kong", code: "HK" },
  { name: "Peru", code: "PE" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Greece", code: "GR" },
  { name: "Romania", code: "RO" },
  { name: "Indonesia", code: "ID" },
  { name: "India", code: "IN" },
  { name: "Russian Federation", code: "RU" },
  { name: "Italy", code: "IT" },
  { name: "Ireland", code: "IE" },
  { name: "Israel", code: "IL" },
  { name: "Germany", code: "DE" },
  { name: "Kenya", code: "KE" },
  { name: "Japan", code: "JP" },
  { name: "Korea, Republic of", code: "KR" },
  { name: "Malaysia", code: "MY" },
  { name: "New Zealand", code: "NZ" },
  { name: "Mexico", code: "MX" },
  { name: "Nigeria", code: "NG" },
  { name: "Netherlands", code: "NL" },
  { name: "Singapore", code: "SG" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "South Africa", code: "ZA" },
  { name: "Taiwan, Province of China", code: "TW" },
  { name: "Thailand", code: "TH" },
  { name: "Turkey", code: "TR" },
  { name: "United States", code: "US" },
  { name: "United Kingdom", code: "GB" },
  { name: "Viet Nam", code: "VN" },
  { name: "Ukraine", code: "UK" },
];

export const CATEGORY = [
  { name: "All", code: "all" },
  { name: "Entertainment", code: "e" },
  { name: "Business", code: "b" },
  { name: "Science/Tech", code: "t" },
  { name: "Health", code: "m" },
  { name: "Sports", code: "s" },
  { name: "Top Stories", code: "h" },
];

export const GEO_TWiTTER = [
  { name: "All", code: "1" },
  { name: "United Arab Emirates", code: "23424738" } , 
  { name: "Algeria", code: "23424740" } , 
  { name: "Argentina", code: "23424747" } , 
  { name: "Australia", code: "23424748" } , 
  { name: "Austria", code: "23424750" } , 
  { name: "Bahrain", code: "23424753" } , 
  { name: "Belgium", code: "23424757" } , 
  { name: "Belarus", code: "23424765" } , 
  { name: "Brazil", code: "23424768" } , 
  { name: "Canada", code: "23424775" } , 
  { name: "Chile", code: "23424782" } , 
  { name: "Colombia", code: "23424787" } , 
  { name: "Denmark", code: "23424796" } , 
  { name: "Dominican Republic", code: "23424800" } , 
  { name: "Ecuador", code: "23424801" } , 
  { name: "Egypt", code: "23424802" } , 
  { name: "Ireland", code: "23424803" } , 
  { name: "France", code: "23424819" } , 
  { name: "Ghana", code: "23424824" } , 
  { name: "Germany", code: "23424829" } , 
  { name: "Greece", code: "23424833" } , 
  { name: "Guatemala", code: "23424834" } , 
  { name: "Indonesia", code: "23424846" } , 
  { name: "India", code: "23424848" } , 
  { name: "Israel", code: "23424852" } , 
  { name: "Italy", code: "23424853" } , 
  { name: "Japan", code: "23424856" } , 
  { name: "Jordan", code: "23424860" } , 
  { name: "Kenya", code: "23424863" } , 
  { name: "Korea", code: "23424868" } , 
  { name: "Kuwait", code: "23424870" } , 
  { name: "Lebanon", code: "23424873" } , 
  { name: "Latvia", code: "23424874" } , 
  { name: "Oman", code: "23424898" } , 
  { name: "Mexico", code: "23424900" } , 
  { name: "Malaysia", code: "23424901" } , 
  { name: "Nigeria", code: "23424908" } , 
  { name: "Netherlands", code: "23424909" } , 
  { name: "Norway", code: "23424910" } , 
  { name: "New Zealand", code: "23424916" } , 
  { name: "Peru", code: "23424919" } , 
  { name: "Pakistan", code: "23424922" } , 
  { name: "Poland", code: "23424923" } , 
  { name: "Panama", code: "23424924" } , 
  { name: "Portugal", code: "23424925" } , 
  { name: "Qatar", code: "23424930" } , 
  { name: "Philippines", code: "23424934" } , 
  { name: "Puerto Rico", code: "23424935" } , 
  { name: "Russia", code: "23424936" } , 
  { name: "Saudi Arabia", code: "23424938" } , 
  { name: "South Africa", code: "23424942" } , 
  { name: "Singapore", code: "23424948" } , 
  { name: "Spain", code: "23424950" } , 
  { name: "Sweden", code: "23424954" } , 
  { name: "Switzerland", code: "23424957" } , 
  { name: "Thailand", code: "23424960" } , 
  { name: "Turkey", code: "23424969" } , 
  { name: "United Kingdom", code: "23424975" } , 
  { name: "Ukraine", code: "23424976" } , 
  { name: "United States", code: "23424977" } , 
  { name: "Venezuela", code: "23424982" } , 
  { name: "Vietnam", code: "23424984" } , 
];

export const CATEGORY_NEWS = [
  { name: "Business", code: "business" },
  { name: "Entertainment", code: "entertainment" },
  { name: "General", code: "general" },
  { name: "Health", code: "health" },
  { name: "Science", code: "science" },
  { name: "Sports", code: "sports" },
  { name: "Technology", code: "technology" },
];
