export const TECH_LIST = [
  "React",
  "JavaScript",
  "Vue",
  "Nest.js",
  "Node.js",
  "Express.js",
  "Java",
  "PHP",
  "Spring",
  "C#",
  "C++",
  "C",
  "Ruby",
  "Mobile",
  "Flutter",
  "ReactNative",
  "Kotlin",
  "Swift",
  ".Net",
  "CSS",
  "SASS",
  "HTML",
  "PM",
  "Scala",
  "ERP",
  "Data",
  "Support",
  "Other",
  "Architecture",
  "Security",
  "Analytics",
  "UX/UI",
  "Admin",
  "DevOps",
  "Testing",
  "Python",
  "Django",
  "Angular",
  "SQL",
  "Mongo",
  "AWS",
  "GitLab",
  "Linux",
  "Git",
  "Docker",
  "REST",
  "Azure",
  "Objective-C",
  "Game",
  "Unity",
  "JIRA",
  "Webpack",
  "Symfony",
];

export const LVL_LIST = ["All", "Junior", "Middle", "Senior"];

export const EMAIL_REGEXP =
  /^(([^<>()[\].,;:\s@"]+(\.[^<>()[\].,;:\s@"]+)*)|(".+"))@(([^<>()[\].,;:\s@"]+\.)+[^<>()[\].,;:\s@"]{2,})$/iu;

export const GITHUB_REGEXP =
  /^(http(s?):\/\/)?(www\.)?github\.([a-z])+\/([A-Za-z0-9]{1,})+\/?$/i;

export const NUMBER_REGEXP = /([0-9])/gm;
